### ISSUE TITLE
Tilde before `\cite` should only complain if there is white space or maybe `}` in front

### ISSUE THREAD

**Issue by jonasc** [jonasbb/pre-commit-latex-hooks#106]
The `tilde-cite` rule is very naive as of now (see also #56) as it always complains if no `~` comes directly before it.
I have a use-case where I give `\cite{...}` as a parameter to another command, i.e., `\command{\cite{...}}`  or `\command[\cite{...}]`. The hook complains about these usages.

I suggest only complaining if `\cite` is preceded by white space or `}` to catch things like `\LaTeX{}\cite{...}`.

**Comment by jonasbb** [comment]
That makes sense. Instead of `[^~]` the regex would use `[\s\}]`. Do you want to submit a PR?

**Comment by jonasc** [comment]
It appears that either GitHub has some hiccups or I'm unable to amend my pull request. Maybe it's just easier if you edit the file directly?
