### ISSUE TITLE
bug in consistent-spelling hook

### ISSUE THREAD

**Issue by neutrinoceros** [jonasbb/pre-commit-latex-hooks#26]
Hi 👋
First of all, thank you for making this project, I've been wishing for something like this and never found the time to implement it myself. I'm really glad you put the effort in to make this public !

I want to report a tiny bug I found with the `consistent-spelling` hook, where the diff-like message is incorrectly printed when one of the lines that it highlights happens to be the last line in a file:
<img width="742" alt="Screenshot 2021-07-01 at 23 44 13" src="https://user-images.githubusercontent.com/14075922/124193249-c812ff00-dac6-11eb-90af-2d8116ab68ad.png">

However it works correctly if I add an empty newline
<img width="742" alt="Screenshot 2021-07-01 at 23 44 23" src="https://user-images.githubusercontent.com/14075922/124193288-dd882900-dac6-11eb-8a29-509376ce9d25.png">

**Comment by jonasbb** [comment]
Thanks. Nice to hear that other people like this selection of hooks. Also thanks for directly providing a PR :)
