### ISSUE TITLE
Example configuration not working

### ISSUE THREAD

**Issue by daniel-mohr** [jonasbb/pre-commit-latex-hooks#35]
The given example configuration in README.md does not work:

```
[ERROR] `cispa-syssec-forbidden-words` is not present in repository https://github.com/jonasbb/pre-commit-latex-hooks.  Typo? Perhaps it is introduced in a newer version?  Often `pre-commit autoupdate` fixes this.
```

Instead it seems to work:

```
...
  - repo: https://github.com/jonasbb/pre-commit-latex-hooks
    rev: v1.2.2
...
```

So, the version number in the example needs to be adapted (at least for 'cispa-syssec-forbidden-words').

**Comment by jonasbb** [comment]
Thanks for the information. That hook is probably not generally useful, so I will remove it from the example. The suggested fix in the error message, running `pre-commit autoupdate` should also work.
