### ISSUE TITLE
Type tag 'tex' is not recognized

### ISSUE THREAD

**Issue by klieret** [jonasbb/pre-commit-latex-hooks#37]
Hi @jonasbb 

First of thanks a lot for your awesome hooks! Since the last version though, I get the following error message:

```
Updating https://github.com/jonasbb/pre-commit-latex-hooks ... 
==> File /home/fuchur/.cache/pre-commit/repoa2l8gbnx/.pre-commit-hooks.yaml
==> At Hook(id='american-eg-ie')
==> At key: types
==> At index 1
=====> Type tag 'tex' is not recognized.  Try upgrading identify and pre-commit?
```

According to https://github.com/pre-commit/pre-commit/issues/855 this seems to have to do with the `types` setting.

**Comment by jonasbb** [comment]
Hi @klieret,

sorry for the trouble, but I cannot reproduce the problem. Both my existing installation and a fresh one work fine. Did you try upgrading both `identify` and `pre-commit`? If that doesn't help could you post steps to reproduce the issue please.

In the last version, I did not change the `types` setting. I only re-ordered the entries in `
.pre-commit-hooks.yaml`.

The linked issue does not seem relevant to me. In the issue the error is produced by a typo.

**Comment by klieret** [comment]
Hey @jonasbb ! Thanks for your quick reply!

I must have messed up something before. Running `pip3 install --upgrade identify` indeed solved the issue for me when I just tried again :)

Sorry for the noise!
