### ISSUE TITLE
Protected space for `\citeauthor`

### ISSUE THREAD

**Issue by DerWeh** [jonasbb/pre-commit-latex-hooks#56]
The hook `tilde-cite` complains that there is no tilde in front of `\citeauthor`.
To my knowledge, this is not necessary, as `\citeauthor` gives just the names, a line break in between doesn't matter.

The same holds probably for the other `\\cite\w+` commands:
```
Text commands:
\citeauthor[〈pre〉][〈post〉]{〈key〉} author list
\citeauthor*[〈pre〉][〈post〉]{〈key〉} compressed author list
\citetitle[〈pre〉][〈post〉]{〈key〉} (short) title
\citetitle*[〈pre〉][〈post〉]{〈key〉} (full) title
\citeyear[〈pre〉][〈post〉]{〈key〉} year
\citedate[〈pre〉][〈post〉]{〈key〉} date
\citeurl[〈pre〉][〈post〉]{〈key〉} URL
```
see http://tug.ctan.org/info/biblatex-cheatsheet/biblatex-cheatsheet.pdf

**Comment by jonasbb** [comment]
Hi, thanks for the report. That seems like an issue indeed. I can change the regex to `[^~]\\cite\b`, then it will only match `\cite` but not the other forms.
